var Chinese = {
  unknow:'未知',
  mainBarTitle:'主页',
  delayBarTitle:'延时',
  channelBarTitle:'通道',
  eqBarTitle:'EQ',
  mixBarTitle:'混音',
  musicBarTitle:'音乐',
  reName:'重命名',
  reNameWarn:'最多四个字节',
  currVersion: '当前版本：',
  armVersion: '\r\nARM版本：',
  machineVersion:'\r\n设备版本：',
  machineId:'\r\n设备地址：',
  modeReset:'场景重置',
  loudSpeakerOutput8: '8喇叭输出',
  loudSpeakerOutput6: '6喇叭输出',
  about:'关于',
  advanceSetup:'高级设置',
  advancedFeaturesEnabled:'高级功能已开启',
  passwordTitle:'请输入密码，用于开启高级功能',
  blueTooth:'蓝牙',
  connected:'已连接',
  unbound:'未绑定',
  modeChoose:'模式选择',
  modeName: [['场景1', '场景2', '场景3'], ['场景4', '场景5', '场景6']],
  switchoverSceneIng:'切换场景中',
  storeModeTitle:'提示',
  storeModeContent:'是否保存当前配置到场景',
  reflashModeIng:'刷新场景中',
  mainVol: '主音量',
  volume: '音量',
  volLock:'音量锁',
  bluetoothConnectionDisconnected: '蓝牙连接已断开',
  disconnectedBluetooth: '已断开蓝牙',
  disconnectBLEfailure: '断开BLE失败',
  openBluetoothAdapterTitle:'提示',
  openBluetoothAdapterContent0: '请确认蓝牙是否打开',
  openBluetoothAdapterContent1: '你的设备可能不支持BLE',
  openBluetoothAdapterContent2: '手机未打开蓝牙，或不支持BLE',
  failConnection:'连接失败',
  failGetBLEDeviceCharacteristics: '获取特征值失败',
  boundSuccess: '绑定成功',
  failNotify: '订阅失败',
  highPass: '高通',
  lowPass: '低通',
  phase_name: ['正相', '反相'],
  filter_name_type: ['预留', '宁克', '贝塞尔', '巴特沃斯'],
  reset: '重置',
  filter: '滤波器',
  ganged: '联动',
  cutOffFrequency: '截至频率',
  affirm: '确 认',
  passwordPlaceholder: '请输入4位密码',
  passwordAuthenticationSuccessful: '密码验证成功',
  wrongPassword: '密码错误！',
  pleaseEnter4Digits: '请输入4位数字',
  switchJointTitle: '提示',
  jointOpen: '开启',
  jointChannel: '通道',
  joint: '的联动 ?',
  copy: '复制',
  data: '数据',
  to: '到',
  close: '关闭',
  millisecond: '毫秒',
  centimeter:'厘米',
  inch:'英寸',
  delaySet:'延时设置',
  eq_id:'序号',
  eq_freq:'频率',
  eq_q:'Q值',
  eq_boost:'增益',
  eq_isThrough:'直通',
  resetEQ:'重置均衡',
  throughAll:'直通所有',
  cancelThrough:'取消直通',
  bluetoothConnected: '蓝牙已连接',
  bluetoothDisconnected: '蓝牙未连接',
  searchEquipment: '搜索设备',
  stopSearch: '停止搜索',
  blueToolthTitle: '提示',
  searchIng:'搜索中...',
  connectionFail: '连接失败',
  failedGetEigenvalue:'获取特征值失败',
  bindingSuccess:'绑定成功',
  subscribeFailure:'订阅失败',
  error:'出错',
  inputTitle0: '输入范围错误！',
  inputTitle1: '不能为空！',
  range:'范围',
  songList:'歌曲列表',
  noMoreSongs:'没有更多歌曲'
}

module.exports = {
  Content: Chinese 
}